#!/usr/bin/env bash
#bash script that install nginx and configures the web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/hs.html
sudo service nginx start
