#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive
name=$(date '+%d-%m-%Y')
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$name".tar.gz backup.sql
