#!/usr/bin/env bash
# This script is displaying the PID of all the bash processes
echo $$ > /var/run/holbertonscript.pid
for (( i=0;;i++ ))
do echo "To infinity and beyond"
    trap "echo Y U no love me?!; exit" SIGINT
    trap "echo I hate the kill command; rm -f /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
    sleep 2
done
