#!/usr/bin/env bash
# This script is displaying the PID of all the bash processes
for (( i=0;;i++ ))
do echo "To infinity and beyond"
trap "echo I am invincible!!!" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/holbertonscript.pid; exit" SIGQUIT SIGTERM
sleep 2
done
