#!/usr/bin/env bash
# Bash script that runs nginx as the nginx user
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user ngix;/' /etc/nginx/nginx.conf
sudo service nginx restart
